### PR TITLE
New Method humanize

### PR DESCRIPTION
**Pull request by Korkey128k**
Add humanize to TimeDifference, for easy human accessible access.
Also modified tests to make them valid.

### CODE REVIEW

**Comment by ffittschen** [comment]
@Korkey128k This PR would implement exactly what I was looking for :+1: But one little thing: When I tried it and there are only seconds, the output is `and 42 Seconds`. Can this `and` be removed if there is only one `diff_part`?

**Comment by Korkey128k** [comment]
Sure, good catch!

**Comment by TopOneOfTopOne** [comment]
Here is a more ruby like version, but missing the addition of "and"

``` ruby
 def humanize
     in_general.collect do |part,quantity|
       next if quantity == 0 
       part = quantity <= 1 ? part.to_s.humanize.singularize : part.to_s.humanize
 
       "#{quantity} #{part}"
     end.compact.join(', ')
   end
 
```

**Comment by tmlee** [comment]
Thank you guys! This is a great add on!

**Pull request merged**
