### PR TITLE
Abs as option

### PR DESCRIPTION
**Pull request by nallwhy**
As a user, I need to get a not abs value sometimes.
So, I added abs as a third param of between method.

The order of param is changed because it's more familiar.
There is no side effects to existing user.

Thanks.

### CODE REVIEW

**Comment by chrisallick** [comment]
I need this! Can we get it merged in?

**Comment by nallwhy** [comment]
@chrisallick I think tmlee doesn't care about this project any more.

**Comment by chrisallick** [comment]
oh cool... lol

**Comment by nallwhy** [comment]
@chrisallick If you want to use abs version, add below to _Gemfile_
```ruby
gem 'time_difference', :git => "git://github.com/nallwhy/time_difference.git", :branch => "abs_as_option"
```

**Comment by tmlee** [comment]
Sorry guys @nallwhy @chrisallick I've gotten quite busy with stuffs.
Just a couple of clarifications

1. Why the swap between `start_time` and `end_time`?
2. Are the specs passing on your machine? If this change has no side effect on existing users, the specs should pass no?

**Comment by nallwhy** [comment]
@tmlee 

1. Because it's more natural to write minuend in front of subtrahend.
2. All specs are passing. The order of argument doesn't have side effect on existing users because original function always returned absolute value.

However, I have another idea that create `diff(end_time, start_time)` function that returns not absolute value.
It can be more clear for users.

**Comment by tmlee** [comment]
@nallwhy 

1. Sorry, i may be out of the loop on this one. Any examples I can refer to on how this is more natural? I didn't think there is a difference. Given a valid case, I would move this to a major release change.

2. Right, if so it is mind boggling why Travis is failing.

Another possibility is to set `abs` like a setting when instantiating the object and such.

**Comment by chrisallick** [comment]
I can't even remember why I needed it anymore :) I think basically it was returning a negative number in some instances.

**Comment by nallwhy** [comment]
@tmlee 
1. B-A. But, I don't think you have to follow my opinion.
2. Your travis CI has been broken.
Please check this issue https://github.com/thoughtbot/factory_girl/pull/846.
```ruby
$ export DEBIAN_FRONTEND=noninteractive
Reading package lists...
Building dependency tree...
Reading state information...
The following extra packages will be installed:
  libc-bin libc-dev-bin libc6-dev
Suggested packages:
  glibc-doc
The following packages will be upgraded:
  libc-bin libc-dev-bin libc6 libc6-dev
4 upgraded, 0 newly installed, 0 to remove and 147 not upgraded.
Need to get 8,840 kB of archives.
After this operation, 4,096 B disk space will be freed.
Get:1 http://us.archive.ubuntu.com/ubuntu/ precise-updates/main libc6-dev amd64 2.15-0ubuntu10.15 [2,943 kB]
Get:2 http://us.archive.ubuntu.com/ubuntu/ precise-updates/main libc-dev-bin amd64 2.15-0ubuntu10.15 [84.7 kB]
Get:3 http://us.archive.ubuntu.com/ubuntu/ precise-updates/main libc-bin amd64 2.15-0ubuntu10.15 [1,177 kB]
Get:4 http://us.archive.ubuntu.com/ubuntu/ precise-updates/main libc6 amd64 2.15-0ubuntu10.15 [4,636 kB]
Fetched 8,840 kB in 0s (16.5 MB/s)
Preconfiguring packages ...
(Reading database ... 124639 files and directories currently installed.)
Preparing to replace libc6-dev 2.15-0ubuntu10.12 (using .../libc6-dev_2.15-0ubuntu10.15_amd64.deb) ...
Unpacking replacement libc6-dev ...
Preparing to replace libc-dev-bin 2.15-0ubuntu10.12 (using .../libc-dev-bin_2.15-0ubuntu10.15_amd64.deb) ...
Unpacking replacement libc-dev-bin ...
Preparing to replace libc-bin 2.15-0ubuntu10.12 (using .../libc-bin_2.15-0ubuntu10.15_amd64.deb) ...
Unpacking replacement libc-bin ...
Processing triggers for man-db ...
Setting up libc-bin (2.15-0ubuntu10.15) ...
(Reading database ... 124638 files and directories currently installed.)
Preparing to replace libc6 2.15-0ubuntu10.12 (using .../libc6_2.15-0ubuntu10.15_amd64.deb) ...
Unpacking replacement libc6 ...
Setting up libc6 (2.15-0ubuntu10.15) ...
Setting up libc-dev-bin (2.15-0ubuntu10.15) ...
Setting up libc6-dev (2.15-0ubuntu10.15) ...
Processing triggers for libc-bin ...
ldconfig deferred processing now taking place
git.checkout
0.75s$ git clone --depth=50 https://github.com/tmlee/time_difference.git tmlee/time_difference
Cloning into 'tmlee/time_difference'...
remote: Counting objects: 166, done.
remote: Compressing objects: 100% (5/5), done.
remote: Total 166 (delta 0), reused 5 (delta 0), pack-reused 161
Receiving objects: 100% (166/166), 21.79 KiB | 0 bytes/s, done.
Resolving deltas: 100% (81/81), done.
Checking connectivity... done.
$ cd tmlee/time_difference
0.57s$ git fetch origin +refs/pull/18/merge:
remote: Counting objects: 9, done.
remote: Compressing objects: 100% (8/8), done.
remote: Total 9 (delta 1), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (9/9), done.
From https://github.com/tmlee/time_difference
 * branch            refs/pull/18/merge -> FETCH_HEAD
$ git checkout -qf FETCH_HEAD
rvm
0.13s$ rvm use 1.9.3 --install --binary --fuzzy
Using /home/travis/.rvm/gems/ruby-1.9.3-p551
$ export BUNDLE_GEMFILE=$PWD/Gemfile.activesupport32
$ ruby --version
ruby 1.9.3p551 (2014-11-13 revision 48407) [x86_64-linux]
$ rvm --version
rvm 1.26.10 (1.26.10) by Wayne E. Seguin <wayneeseguin@gmail.com>, Michal Papis <mpapis@gmail.com> [https://rvm.io/]
$ bundle --version
Bundler version 1.7.6
$ gem --version
2.5.1
12.69s$ bundle install --jobs=3 --retry=3
Fetching gem metadata from https://rubygems.org/...........
Resolving dependencies...
Installing i18n 0.7.0
Installing rake 11.1.2
Installing multi_json 1.12.1
Installing diff-lcs 1.2.5
Installing rspec-core 2.13.1
Using bundler 1.7.6
Installing rspec-mocks 2.13.1
Installing rspec-expectations 2.13.0
Installing activesupport 3.2.22.2
NoMethodError: undefined method `spec' for nil:NilClass
Installing rspec 2.13.0
An error occurred while installing time_difference (0.4.2), and Bundler cannot
continue.
Make sure that `gem install time_difference -v '0.4.2'` succeeds before
bundling.
```

**Pull request closed without merging**
